# Site wide configuration

title: "Fimo"
description: "Blog For My Educational Purpose, Sharing Some Information, and Stories"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url:
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name: Filfimo Yulfiz Ahsanul Hulqi
  email: yulfisahsan@gmail.com
  twitter: filfimohulqi
  google:
    ad-client:
    ad-slot:
  bio: Not tech enthusiast
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: Fimo


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
